import { useEffect, useState } from "react";
import { Bike, MapPin, Plus, Power } from "lucide-react";
import { initialCouriers, initialZones } from "../data/delivery";
import { supabase } from "../lib/supabase";
import type { Courier, DeliveryZone } from "../types";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function DeliverySettings() {
  const [zones, setZones] = useState<DeliveryZone[]>(initialZones);
  const [couriers, setCouriers] = useState<Courier[]>(initialCouriers);
  useEffect(() => { if (!supabase) return; Promise.all([supabase.from("delivery_zones").select("id,neighborhood,fee,eta_minutes,active").order("neighborhood"), supabase.from("couriers").select("id,name,phone,vehicle,active").order("name")]).then(([zoneResult, courierResult]) => { if (zoneResult.data) setZones(zoneResult.data.map((row) => ({ id: row.id, neighborhood: row.neighborhood, fee: Number(row.fee), etaMinutes: row.eta_minutes, active: row.active }))); if (courierResult.data) setCouriers(courierResult.data.map((row) => ({ id: row.id, name: row.name, phone: row.phone, vehicle: row.vehicle, active: row.active }))); }); }, []);
  async function addZone() { const neighborhood = window.prompt("Nome do bairro:")?.trim(); if (!neighborhood || !supabase) return; const fee = Number(window.prompt("Taxa de entrega:", "5")?.replace(",", ".") ?? 0); const { data } = await supabase.from("delivery_zones").insert({ store_id: "10000000-0000-4000-8000-000000000001", neighborhood, fee: Number.isFinite(fee) ? fee : 0, eta_minutes: 45, active: true }).select("id,neighborhood,fee,eta_minutes,active").single(); if (data) setZones((current) => [...current, { id: data.id, neighborhood: data.neighborhood, fee: Number(data.fee), etaMinutes: data.eta_minutes, active: data.active }]); }
  async function addCourier() { const name = window.prompt("Nome do entregador:")?.trim(); if (!name || !supabase) return; const phone = window.prompt("Telefone:")?.trim() ?? ""; const { data } = await supabase.from("couriers").insert({ store_id: "10000000-0000-4000-8000-000000000001", name, phone, vehicle: "Moto", active: true }).select("id,name,phone,vehicle,active").single(); if (data) setCouriers((current) => [...current, { id: data.id, name: data.name, phone: data.phone, vehicle: data.vehicle, active: data.active }]); }
  async function toggleZone(zone: DeliveryZone) { setZones((current) => current.map((item) => item.id === zone.id ? { ...item, active: !item.active } : item)); await supabase?.from("delivery_zones").update({ active: !zone.active }).eq("id", zone.id); }
  async function toggleCourier(courier: Courier) { setCouriers((current) => current.map((item) => item.id === courier.id ? { ...item, active: !item.active } : item)); await supabase?.from("couriers").update({ active: !courier.active }).eq("id", courier.id); }
  return <section className="content delivery-settings"><div className="title-row"><div><p className="eyebrow">LOGÍSTICA</p><h1>Entrega e retirada</h1><p>Configure bairros, taxas e a equipe de entrega.</p></div></div><div className="delivery-columns"><article className="delivery-panel"><header><div><MapPin /><div><h2>Bairros atendidos</h2><p>Taxa e prazo estimado por região.</p></div></div><button className="primary" onClick={addZone}><Plus size={16} /> Bairro</button></header><div className="zone-list">{zones.map((zone) => <div key={zone.id}><span className="zone-icon"><MapPin size={17} /></span><div><strong>{zone.neighborhood}</strong><small>Estimativa: {zone.etaMinutes} minutos</small></div><b>{zone.fee ? money.format(zone.fee) : "Grátis"}</b><button className={zone.active ? "toggle-on" : ""} onClick={() => toggleZone(zone)}><Power size={15} /></button></div>)}</div></article><article className="delivery-panel"><header><div><Bike /><div><h2>Entregadores</h2><p>Equipe disponível para os pedidos.</p></div></div><button className="primary" onClick={addCourier}><Plus size={16} /> Entregador</button></header><div className="courier-list">{couriers.map((courier) => <div key={courier.id}><span className="courier-avatar">{courier.name.slice(0, 1).toUpperCase()}</span><div><strong>{courier.name}</strong><small>{courier.vehicle}{courier.phone ? ` • ${courier.phone}` : ""}</small></div><span className={courier.active ? "courier-online" : "courier-offline"}>{courier.active ? "Disponível" : "Inativo"}</span><button className={courier.active ? "toggle-on" : ""} onClick={() => toggleCourier(courier)}><Power size={15} /></button></div>)}</div></article></div></section>;
}
