import { Bike, MapPin, Plus, Power } from "lucide-react";
import { initialCouriers, initialZones } from "../data/delivery";
import { usePersistentState } from "../hooks/usePersistentState";
import type { Courier, DeliveryZone } from "../types";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function DeliverySettings() {
  const [zones, setZones] = usePersistentState<DeliveryZone[]>("braseira:delivery-zones", initialZones);
  const [couriers, setCouriers] = usePersistentState<Courier[]>("braseira:couriers", initialCouriers);
  function addZone() { const neighborhood = window.prompt("Nome do bairro:")?.trim(); if (!neighborhood) return; const fee = Number(window.prompt("Taxa de entrega:", "5")?.replace(",", ".") ?? 0); setZones((current) => [...current, { id: crypto.randomUUID(), neighborhood, fee: Number.isFinite(fee) ? fee : 0, etaMinutes: 45, active: true }]); }
  function addCourier() { const name = window.prompt("Nome do entregador:")?.trim(); if (!name) return; const phone = window.prompt("Telefone:")?.trim() ?? ""; setCouriers((current) => [...current, { id: crypto.randomUUID(), name, phone, vehicle: "Moto", active: true }]); }
  return <section className="content delivery-settings"><div className="title-row"><div><p className="eyebrow">LOGÍSTICA</p><h1>Entrega e retirada</h1><p>Configure bairros, taxas e a equipe de entrega.</p></div></div><div className="delivery-columns"><article className="delivery-panel"><header><div><MapPin /><div><h2>Bairros atendidos</h2><p>Taxa e prazo estimado por região.</p></div></div><button className="primary" onClick={addZone}><Plus size={16} /> Bairro</button></header><div className="zone-list">{zones.map((zone) => <div key={zone.id}><span className="zone-icon"><MapPin size={17} /></span><div><strong>{zone.neighborhood}</strong><small>Estimativa: {zone.etaMinutes} minutos</small></div><b>{zone.fee ? money.format(zone.fee) : "Grátis"}</b><button className={zone.active ? "toggle-on" : ""} onClick={() => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, active: !item.active } : item))}><Power size={15} /></button></div>)}</div></article><article className="delivery-panel"><header><div><Bike /><div><h2>Entregadores</h2><p>Equipe disponível para os pedidos.</p></div></div><button className="primary" onClick={addCourier}><Plus size={16} /> Entregador</button></header><div className="courier-list">{couriers.map((courier) => <div key={courier.id}><span className="courier-avatar">{courier.name.slice(0, 1).toUpperCase()}</span><div><strong>{courier.name}</strong><small>{courier.vehicle}{courier.phone ? ` • ${courier.phone}` : ""}</small></div><span className={courier.active ? "courier-online" : "courier-offline"}>{courier.active ? "Disponível" : "Inativo"}</span><button className={courier.active ? "toggle-on" : ""} onClick={() => setCouriers((current) => current.map((item) => item.id === courier.id ? { ...item, active: !item.active } : item))}><Power size={15} /></button></div>)}</div></article></div></section>;
}
