import { Banknote, BarChart3, ChefHat, Clock3, CreditCard, Flame, PackageCheck, QrCode, ShoppingBag } from "lucide-react";
import { usePersistentState } from "../hooks/usePersistentState";
import type { CashSession, Order, OrderStatus } from "../types";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function Operations({ view }: { view: "dashboard" | "kitchen" | "cash" }) {
  const [orders, setOrders] = usePersistentState<Order[]>("braseira:orders", []);
  const [cash, setCash] = usePersistentState<CashSession[]>("braseira:cash-sessions", []);
  const today = new Date().toISOString().slice(0, 10);
  const todayOrders = orders.filter((order) => order.createdAt.slice(0, 10) === today && order.status !== "cancelled");
  const completed = todayOrders.filter((order) => order.status === "delivered");
  const revenue = completed.reduce((sum, order) => sum + order.total, 0);
  const activeCash = cash.find((session) => !session.closedAt);
  function move(id: string, status: OrderStatus) { setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)); }
  function openCash() { const value = Number(window.prompt("Valor inicial do caixa:", "150")?.replace(",", ".") ?? 0); setCash((current) => [{ id: crypto.randomUUID(), openedAt: new Date().toISOString(), openingAmount: value }, ...current]); }
  function closeCash() { if (!activeCash) return; const value = Number(window.prompt("Valor contado no caixa:", String(activeCash.openingAmount + revenue))?.replace(",", ".") ?? 0); setCash((current) => current.map((session) => session.id === activeCash.id ? { ...session, closedAt: new Date().toISOString(), closingAmount: value } : session)); }

  if (view === "kitchen") {
    const columns: { status: OrderStatus; title: string }[] = [{ status: "confirmed", title: "Aguardando preparo" }, { status: "preparing", title: "Em preparo" }, { status: "ready", title: "Prontos" }];
    return <section className="content kitchen"><div className="title-row"><div><p className="eyebrow">TELA DA COZINHA</p><h1>Produção</h1><p>Organize os pedidos por etapa de preparo.</p></div><span className="live-badge"><i /> Cozinha online</span></div><div className="kitchen-board">{columns.map((column) => <div className={`kitchen-column kitchen-${column.status}`} key={column.status}><header><span>{column.title}</span><b>{orders.filter((item) => item.status === column.status).length}</b></header>{orders.filter((item) => item.status === column.status).map((order) => <article key={order.id}><div><span>#{String(order.number).padStart(3, "0")}</span><b>{new Date(order.createdAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</b></div><h2>{order.customerName}</h2>{order.items.map((item) => <p key={item.id}><strong>{item.quantity}× {item.name}</strong><small>{item.detail}</small></p>)}<button onClick={() => move(order.id, column.status === "confirmed" ? "preparing" : column.status === "preparing" ? "ready" : "delivered")}>{column.status === "confirmed" ? <><Flame size={16} /> Iniciar preparo</> : column.status === "preparing" ? <><PackageCheck size={16} /> Marcar pronto</> : <><ShoppingBag size={16} /> Liberar pedido</>}</button></article>)}</div>)}</div></section>;
  }

  if (view === "cash") {
    const payment = (method: Order["paymentMethod"]) => completed.filter((order) => order.paymentMethod === method).reduce((sum, order) => sum + order.total, 0);
    return <section className="content cash-page"><div className="title-row"><div><p className="eyebrow">FINANCEIRO DO DIA</p><h1>Caixa e relatórios</h1><p>Acompanhe recebimentos e fechamento diário.</p></div>{activeCash ? <button className="close-cash" onClick={closeCash}>Fechar caixa</button> : <button className="primary" onClick={openCash}><Banknote size={17} /> Abrir caixa</button>}</div><div className={`cash-status ${activeCash ? "open" : "closed"}`}><div><Banknote /><span>{activeCash ? "Caixa aberto" : "Caixa fechado"}<small>{activeCash ? `Aberto às ${new Date(activeCash.openedAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}` : "Abra o caixa para iniciar o movimento"}</small></span></div>{activeCash && <strong>Fundo: {money.format(activeCash.openingAmount)}</strong>}</div><div className="payment-cards"><article><Banknote /><span>Dinheiro<strong>{money.format(payment("cash"))}</strong></span></article><article><QrCode /><span>PIX<strong>{money.format(payment("pix"))}</strong></span></article><article><CreditCard /><span>Cartões<strong>{money.format(payment("card"))}</strong></span></article><article><BarChart3 /><span>Total recebido<strong>{money.format(revenue)}</strong></span></article></div><div className="report-table"><header><h2>Pedidos finalizados hoje</h2><span>{completed.length} vendas</span></header>{completed.length === 0 ? <p className="no-sales">Ainda não existem pedidos entregues hoje.</p> : completed.map((order) => <div key={order.id}><span>#{String(order.number).padStart(3, "0")}</span><b>{order.customerName}</b><span>{order.paymentMethod === "pix" ? "PIX" : order.paymentMethod === "cash" ? "Dinheiro" : "Cartão"}</span><strong>{money.format(order.total)}</strong></div>)}</div></section>;
  }

  const maxRevenue = Math.max(1, revenue);
  return <section className="content dashboard-page"><div className="title-row"><div><p className="eyebrow">VISÃO GERAL</p><h1>Olá, Braseira!</h1><p>Acompanhe os principais números da operação de hoje.</p></div><span className="dashboard-date">{new Date().toLocaleDateString("pt-BR", { weekday: "long", day: "2-digit", month: "long" })}</span></div><div className="dashboard-metrics"><article><span><ShoppingBag /></span><div>Pedidos hoje<strong>{todayOrders.length}</strong><small>{todayOrders.filter((item) => !["delivered"].includes(item.status)).length} ativos</small></div></article><article><span><Banknote /></span><div>Faturamento<strong>{money.format(revenue)}</strong><small>Pedidos entregues</small></div></article><article><span><Clock3 /></span><div>Ticket médio<strong>{money.format(completed.length ? revenue / completed.length : 0)}</strong><small>{completed.length} finalizados</small></div></article><article><span><ChefHat /></span><div>Na cozinha<strong>{orders.filter((item) => ["confirmed", "preparing"].includes(item.status)).length}</strong><small>Aguardando ou preparando</small></div></article></div><div className="dashboard-grid"><article className="revenue-panel"><header><div><h2>Receita por pagamento</h2><p>Distribuição dos pedidos finalizados.</p></div><strong>{money.format(revenue)}</strong></header>{(["pix", "cash", "card"] as const).map((method) => { const value = completed.filter((order) => order.paymentMethod === method).reduce((sum, order) => sum + order.total, 0); return <div className="revenue-bar" key={method}><span>{method === "pix" ? "PIX" : method === "cash" ? "Dinheiro" : "Cartão"}</span><i><b style={{ width: `${(value / maxRevenue) * 100}%` }} /></i><strong>{money.format(value)}</strong></div> })}</article><article className="recent-panel"><header><h2>Pedidos recentes</h2><span>{orders.length} no histórico</span></header>{orders.slice(0, 5).map((order) => <div key={order.id}><span>#{String(order.number).padStart(3, "0")}</span><div><strong>{order.customerName}</strong><small>{order.items.length} itens • {order.deliveryType === "delivery" ? "Entrega" : "Retirada"}</small></div><b>{money.format(order.total)}</b></div>)}{orders.length === 0 && <p>Nenhum pedido ainda.</p>}</article></div></section>;
}
