import { BellRing, CheckCircle2, ChefHat, Clock3, PackageCheck, XCircle } from "lucide-react";
import { useOnlineOrders } from "../hooks/useOnlineOrders";
import type { OrderStatus } from "../types";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const statusLabel: Record<OrderStatus, string> = { pending: "Novo", confirmed: "Confirmado", preparing: "Em preparo", ready: "Pronto", delivered: "Entregue", cancelled: "Cancelado" };
const nextStatus: Partial<Record<OrderStatus, OrderStatus>> = { pending: "confirmed", confirmed: "preparing", preparing: "ready", ready: "delivered" };
const nextLabel: Partial<Record<OrderStatus, string>> = { pending: "Confirmar pedido", confirmed: "Iniciar preparo", preparing: "Marcar como pronto", ready: "Finalizar entrega" };

export default function OrdersBoard() {
  const { orders, couriers, error: loadError, newOrderId, updateStatus, assignCourier } = useOnlineOrders();
  const active = orders.filter((order) => !["delivered", "cancelled"].includes(order.status));
  function update(id: string, status: OrderStatus) { updateStatus(id, status); }
  return <section className="content orders-board"><div className="title-row"><div><p className="eyebrow">CENTRAL DE OPERAÇÃO</p><h1>Pedidos</h1><p>Acompanhe os pedidos recebidos e atualize cada etapa.</p></div><span className="live-badge"><i /> Atualização automática</span></div>
    {newOrderId && <div className="new-order-alert" role="status"><BellRing size={20} /><div><strong>Novo pedido recebido!</strong><span>A venda já apareceu no início da lista.</span></div></div>}{loadError && <p className="admin-login-error" role="alert">{loadError}</p>}<div className="stats"><article><span>Pedidos ativos</span><strong>{active.length}</strong></article><article><span>Aguardando confirmação</span><strong>{orders.filter((item) => item.status === "pending").length}</strong></article><article><span>Em preparo</span><strong>{orders.filter((item) => item.status === "preparing").length}</strong></article></div>
    {orders.length === 0 ? <div className="orders-empty"><Clock3 size={42} /><h2>Nenhum pedido recebido</h2><p>Faça um pedido pelo cardápio público para testar o fluxo.</p></div> : <div className="orders-list">{orders.map((order) => <article className={`order-card status-${order.status}${order.id === newOrderId ? " just-arrived" : ""}`} key={order.id}><header><div><span>Pedido #{String(order.number).padStart(3, "0")}</span><h2>{order.customerName}</h2><small>{new Date(order.createdAt).toLocaleString("pt-BR", { hour: "2-digit", minute: "2-digit" })} • {order.deliveryType === "delivery" ? "Entrega" : "Retirada"}</small></div><b>{statusLabel[order.status]}</b></header><div className="order-items">{order.items.map((item) => <p key={item.id}><span>{item.quantity}× {item.name}<small>{item.detail}</small></span><b>{money.format(item.price * item.quantity)}</b></p>)}</div><div className="order-customer"><p><strong>Contato:</strong> {order.phone}</p>{order.address && <p><strong>Endereço:</strong> {order.address}</p>}<p><strong>Pagamento:</strong> {order.paymentMethod === "pix" ? "PIX" : order.paymentMethod === "cash" ? "Dinheiro" : "Cartão"}</p>{order.deliveryType === "delivery" && <label className="courier-select">Entregador<select value={order.courierId ?? ""} onChange={(event) => assignCourier(order.id, event.target.value)}><option value="">Atribuir depois</option>{couriers.filter((courier) => courier.active).map((courier) => <option key={courier.id} value={courier.id}>{courier.name} • {courier.vehicle}</option>)}</select></label>}{order.notes && <p><strong>Observações:</strong> {order.notes}</p>}</div><footer><div><span>Total</span><strong>{money.format(order.total)}</strong></div><div className="order-actions">{nextStatus[order.status] && <button className="advance-order" onClick={() => update(order.id, nextStatus[order.status]!)}>{order.status === "preparing" ? <PackageCheck size={17} /> : order.status === "confirmed" ? <ChefHat size={17} /> : <CheckCircle2 size={17} />}{nextLabel[order.status]}</button>}{!["delivered", "cancelled"].includes(order.status) && <button className="cancel-order" onClick={() => update(order.id, "cancelled")}><XCircle size={17} /></button>}</div></footer></article>)}</div>}
  </section>;
}
